/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_CMG.h"
#include "Clock_1.h"
#include "flywheel_motor_aliases.h"
#include "flywheel_motor.h"
#include "gimbal_motor_aliases.h"
#include "gimbal_motor.h"
#include "gimbal_direction_aliases.h"
#include "gimbal_direction.h"
#include "UART.h"
#include "Rpi_Tx_Interrupt.h"
#include "VDAC8_1.h"
#include "Clock_3.h"
#include "Gimbal_Timer.h"
#include "Gimbal_Control_Loop_Interrupt.h"
#include "Timer_Interrupt.h"
#include "Gimbal_Encoder_A_aliases.h"
#include "Gimbal_Encoder_A.h"
#include "SW1_aliases.h"
#include "SW1.h"
#include "LED1_aliases.h"
#include "LED1.h"
#include "Gimbal_Encoder.h"
#include "Gimbal_Encoder_B_aliases.h"
#include "Gimbal_Encoder_B.h"
#include "Clock_2.h"
#include "Handle_Encoder.h"
#include "Handle_Encoder_A_aliases.h"
#include "Handle_Encoder_A.h"
#include "Clock_4.h"
#include "Handle_Encoder_B_aliases.h"
#include "Handle_Encoder_B.h"
#include "Steering_Timer.h"
#include "Steering_Control_Loop_Interrupt.h"
#include "Clock_5.h"
#include "Steering_PWM_aliases.h"
#include "Steering_PWM.h"
#include "Steering_Dir_aliases.h"
#include "Steering_Dir.h"
#include "PWM_Steer.h"
#include "Clock_6.h"
#include "UART_IntClock.h"
#include "Gimbal_Encoder_Cnt16.h"
#include "Handle_Encoder_Cnt16.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

