# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\jebush2\Desktop\PSoC 3-19-2019\Smart Bike PSoC\CMG_New.cydsn\CMG_New.cyprj
# Date: Fri, 26 Apr 2019 18:54:19 GMT
#set_units -time ns
create_clock -name {Clock_2(routed)} -period 100000 -waveform {0 50000} [list [get_pins {ClockBlock/dclk_5}]]
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {timer_clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 13 25} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {UART_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 53 105} -nominal_period 2166.6666666666665 [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 241 481} [list [get_pins {ClockBlock/dclk_glb_3}]]
create_generated_clock -name {Clock_4} -source [get_pins {ClockBlock/clk_sync}] -edges {1 1001 2001} -nominal_period 41666.666666666664 [list [get_pins {ClockBlock/dclk_glb_4}]]
create_generated_clock -name {Clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2401 4801} [list [get_pins {ClockBlock/dclk_glb_5}]]
create_generated_clock -name {Clock_7} -source [get_pins {ClockBlock/clk_sync}] -edges {1 9 17} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {Clock_3} -source [get_pins {ClockBlock/clk_sync}] -edges {1 24001 48001} [list [get_pins {ClockBlock/dclk_glb_6}]]
create_generated_clock -name {Clock_6} -source [get_pins {ClockBlock/clk_sync}] -edges {1 24001 48001} [list [get_pins {ClockBlock/dclk_glb_7}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for C:\Users\jebush2\Desktop\PSoC 3-19-2019\Smart Bike PSoC\CMG_New.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\jebush2\Desktop\PSoC 3-19-2019\Smart Bike PSoC\CMG_New.cydsn\CMG_New.cyprj
# Date: Fri, 26 Apr 2019 18:54:06 GMT
